/*
 * PdfView.swift
 *
 * Author: Bouchra Mohamed Lemine
 * Date: 03/04/2024
 *
 * Description: The content of the PDF file used to export the skin lesion.
 */


import SwiftUI



struct PdfView: View {
    
    @State var file: File
    @State var uiImage: UIImage
    
    let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MM/yyyy, hh:mm a"
        return formatter
    }()
    
    var body: some View {
        
        VStack {
            
            // The headline
            Text("Report generated by Skan")
                .font(.system(
                    size: 20,
                    weight: .bold,
                    design: .default)
                ).padding(.vertical, 40)
            
            
            // The skin lesion photo.
            Image(uiImage: uiImage)
                .resizable()
                .frame(width: 300, height: 400)
                .clipShape(.rect(cornerRadius: 20))
                .padding(.bottom, 40)
                .padding(.top, 30)


            // The date and time at which the photo was taken.
            Text(dateFormatter.string(from: file.date))
                .font(.system(
                size: 18,
                weight: .bold,
                design: .default)
            ).padding(.bottom, 40)
                     

            // The diagnosis of the skin lesion.
            Text("\(file.diagnosis) Skin Lesion")
                .font(.system(
                size: 25,
                weight: .heavy,
                design: .default)
                ).foregroundColor(.color2)
            .padding(.bottom, 50)

        }.padding(0)
    }
}

 
